#!/bin/sh

set -eu

sv check rpcbind >/dev/null
sv check dbus-daemon >/dev/null

rm -rf /run/ganesha/
mkdir -p /run/ganesha/

exec 2>&1
exec ganesha.nfsd -F -L /dev/stdout -f /etc/ganesha/ganesha.conf
